#!/bin/sh
#
# ebaytoold
#
# chkconfig: - 85 15
# description: ebaytool daemon
#

CP=/var/www/ebaytool/struts2/target/classes/

for jar in `ls /usr/local/apache-tomcat-7.0.2/webapps/ROOT/WEB-INF/lib/`
do
	CP=$CP:/usr/local/apache-tomcat-7.0.2/webapps/ROOT/WEB-INF/lib/$jar
done

start() {
	/usr/local/jdk1.6.0_21/bin/java -cp $CP ebaytool.apicall.Daemon start \
		> /var/www/ebaytool/logs/daemon.log &
}

stop() {
	/usr/local/jdk1.6.0_21/bin/java -cp $CP ebaytool.apicall.Daemon stop
	sleep 5
	ps auxw | grep java
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		stop
		start
		;;
	*)
		echo $"Usage: $prog {start|stop|restart}"
esac
